php:
  build: .
  container_name: php_php72maria103
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links: 
    - db  

db:
  image: mariadb:10.3
  container_name: db_php72maria103
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=php
   - MYSQL_DATABASE=php

#phpmyadmin o port 8080
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin_php72maria103
  links: 
   - db
  ports: 
   - "8080:80"
  environment:
   - PMA_USER=root
   - PMA_PASSWORD=php
