php:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links: 
    - db  
  container_name: php_php56maria103

db:
  image: mariadb:10.3
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=php
   - MYSQL_DATABASE=php
  container_name: db_php56maria103
#phpmyadmin o port 8080
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin_php56maria103
  links: 
   - db
  ports: 
   - "8080:80"
  environment:
   - PMA_USER=root
   - PMA_PASSWORD=php
