version: '3'
services:
  db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=rails
     - MYSQL_DATABASE=rail
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  #phpmyadmin o port 8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
     - db
    ports: 
     - "8080:80"
    environment:
     - PMA_USER=root
     - PMA_PASSWORD=rails
