php:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links: 
    - db  
  container_name: php_php56mysql57

db:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=php
   - MYSQL_DATABASE=php
  container_name: db_php56mysql57
#phpmyadmin o port 8080
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin_php56mysql57
  links: 
   - db
  ports: 
   - "8080:80"
  environment:
   - PMA_USER=root
   - PMA_PASSWORD=php
