version: '2'
services:
  php:
    build: .
#   container_name: php_php83maria115
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    links: 
      - db  

  db:
    image: mariadb:11.5
#   container_name: db_php83maria115
    volumes:
     - ./data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=php
     - MYSQL_DATABASE=php

#phpmyadmin o port 8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
#   container_name: phpmyadmin_php83maria115
    links: 
     - db
    ports: 
     - "8080:80"
    environment:
     - PMA_USER=root
     - PMA_PASSWORD=php
